### ISSUE TITLE
Campos opcionais na interface CreateTransactionInputBase

### ISSUE THREAD

**Issue by thuram** [jonyw4/pagarme-js-types#23]
Pessoal, tudo bem? Gostaria de saber como fazer para remover os campos `customer` e `items` do `CreateTransactionInputBase`. Esses campos são obrigatórios apenas com antifraude e estou desenvolvendo um projeto que ele ficará desabilitado, ou seja, esses campos não serão enviados. 

Qual a melhor forma de fazer essa alteração?

**Comment by mrlmaia** [comment]
Você pode alterar 'hard coded'. Usando o VsCode você vai dar um ctrl+click na função que você quer alterar e, ele vai levar você na declaração de tipagem da função. Nela basta você adicionar um ? na frente do campo. Ex.: 
```ts
interface CreateTransactionInputBase {
  // ...
  items: ItemInput[];
}
```
Altere para 
```ts
interface CreateTransactionInputBase {
  // ...
  items?: ItemInput[];
}
```

**Comment by thuram** [comment]
> Você pode alterar 'hard coded'. Usando o VsCode você vai dar um ctrl+click na função que você quer alterar e, ele vai levar você na declaração de tipagem da função. Nela basta você adicionar um ? na frente do campo. Ex.:
> 
> ```ts
> interface CreateTransactionInputBase {
>   // ...
>   items: ItemInput[];
> }
> ```
> 
> Altere para
> 
> ```ts
> interface CreateTransactionInputBase {
>   // ...
>   items?: ItemInput[];
> }
> ```

Eu até pensei em fazer isso, mas não é uma prática ruim alterar os arquivos que estão na pasta node_modules? Porque a pasta node_modules está dentro do .gitignore. Como eu vou refletir essa modificação em produção? 

Desulpa se essa pergunta parece meio besta, mas comecei com TS tem pouco tempo kk

**Comment by mrlmaia** [comment]
> > Você pode alterar 'hard coded'. Usando o VsCode você vai dar um ctrl+click na função que você quer alterar e, ele vai levar você na declaração de tipagem da função. Nela basta você adicionar um ? na frente do campo. Ex.:
> > ```ts
> > interface CreateTransactionInputBase {
> >   // ...
> >   items: ItemInput[];
> > }
> > ```
> > 
> > 
> > Altere para
> > ```ts
> > interface CreateTransactionInputBase {
> >   // ...
> >   items?: ItemInput[];
> > }
> > ```
> 
> Eu até pensei em fazer isso, mas não é uma prática ruim alterar os arquivos que estão na pasta node_modules? Porque a pasta node_modules está dentro do .gitignore. Como eu vou refletir essa modificação em produção?
> 
> Desulpa se essa pergunta parece meio besta, mas comecei com TS tem pouco tempo kk

@thuram  Até seria mas como você está alterando uma lib de tipagem não faz diferença porque ela é uma dependência de desenvolvimento, ou seja, não vai pra produção

**Comment by jonyw4** [comment]
Muito legal ver a discussão de vocês aqui na issue, eu acabei não recebendo notificação então cheguei meio atrasado. 😅
Eu não recomendo a solução que @mrlmaia, apesar dela funcionar, o fato de que se você atualizar a pasta `node_modules` seja atualizando a versão dessa tipagem ou reinstalando o seu projeto, você vai acabar perdendo essa alteração *hard-coded* cedo ou tarde.

Nesse mês eu acredito que eu não trabalhar nesse repositório, então provavelmente não poderei fazer a tipagem de fato, mas todo Pull Request é bem-vindo. Se você acredita que pode melhorar a tipagem ou corrigi-la, pode abrir um PR apontando a documentação do Pagar.me que lerei com muito prazer! 😁

Ah, esse repositório  não é oficial ok? O Pagar.me não quer manter a tipagem do *client *deles como apontado[ nessa issue](https://github.com/pagarme/pagarme-js/issues/212), então atualmente só eu mantenho o repositório ativo [sempre expondo os colaboradores](https://github.com/jonyw4/pagarme-js-types#contributors-).
