### ISSUE TITLE
client.security.encrypt() params

### ISSUE THREAD

**Issue by mrlmaia** [jonyw4/pagarme-js-types#24]
The encrypt method is typed as  `function encrypt(opts: any, card: any): any;` but in the official documentation the same method is used  `client.security.encrypt(card))`

**Comment by jonyw4** [comment]
Fala @mrlmaia, tudo certo?

Nesse mês eu acredito que eu não trabalhar nesse repositório, então provavelmente não poderei fazer a tipagem de fato, mas todo Pull Request é bem-vindo. Se você acredita que pode melhorar a tipagem ou corrigi-la, pode abrir um PR apontando a documentação do Pagar.me que lerei com muito prazer! 😁

**Comment by jonyw4** [comment]
Eu não percebi, mas como você enviou como _chore_ acabou que não lançou nesse release. Eu vou tentar enviar alguma outra correção para disparar o envio no _npm_
