### ISSUE TITLE
Porque Document estende Address?

### ISSUE THREAD

**Issue by italodeandra** [jonyw4/pagarme-js-types#29]
Olá pessoal, tudo bem?

Muito obrigado por compartilharem os types do pagarme. Atualmente estou implementando em meu projeto e estou tendo alguns problemas, irei postar aqui aos poucos e caso concordem que seja um problema eu poderei contribuir caso estejam ocupados.

Mas enfim, pq *Document* estende *Address*?

https://github.com/jonyw4/pagarme-js-types/blob/9f00a58fb89317d92b8c56fe921c46ba3fd28172/index.d.ts#L489

Sendo que a API aceita apenas os campos `type` e `number`. Estou tendo que contornar isso convertendo o tipo.

Abraços.

**Comment by jonyw4** [comment]
Fala @italodeandra. Eu acabei criando esse repo a partir de uma discussão que teve la no repositório do pagar.me, infelizmente eles não estão mantendo a tipagem do projeto (o que é uma pena). Toda e qualquer contribuição é bem-vinda! Criei o repositório para facilitar a manutenção desse código com todo mundo mesmo! 😁

Sobre a sua pergunta, a resposta é: eu não sei. 😂
Eu acredito que ou a documentação estava errada, ou eu me confundi na hora de criar essa interface. [Mas realmente um Document não estende um Address . ](https://docs.pagar.me/reference#objeto-documents-documentos), então é um bug. Se você puder mandar um PR eu agradeço e lerei com muito prazer!
