### ISSUE TITLE
O campo "type" em "Document" deveria aceitar os valores "cpf" ou "cnpj"

### ISSUE THREAD

**Issue by italodeandra** [jonyw4/pagarme-js-types#30]
Eu tenho o tipo *DocumentType*:

https://github.com/jonyw4/pagarme-js-types/blob/9f00a58fb89317d92b8c56fe921c46ba3fd28172/index.d.ts#L487

Que quando utilizado em *Customer* está correto: 

https://github.com/jonyw4/pagarme-js-types/blob/9f00a58fb89317d92b8c56fe921c46ba3fd28172/index.d.ts#L496-L501

Mas está errado quando utilizado em *Document* pois os valores permitidos são `cpf` ou `cnpj`:

https://github.com/jonyw4/pagarme-js-types/blob/9f00a58fb89317d92b8c56fe921c46ba3fd28172/index.d.ts#L489-L491

Isso é alguma inconsistência por conta da versão que estou utilizando ou é um erro mesmo?

**Comment by mrlmaia** [comment]
Já enviei uma pull request resolvendo isso #33
