### ISSUE TITLE
O enum "Country" deveria ser em caixa baixa respeitando a expressão regular "[a-z]{2}"

### ISSUE THREAD

**Issue by italodeandra** [jonyw4/pagarme-js-types#31]
De acordo com a API os campos "Country" aceitam apenas valores em *lowercase* e o enum está em *UPPERCASE*.

**Comment by jonyw4** [comment]
Obg por apontar o problema @italodeandra! Nesse mês eu acredito que eu não trabalhar nesse repositório, então provavelmente não poderei fazer a tipagem de fato, mas todo Pull Request é bem-vindo. Se você acredita que pode melhorar a tipagem ou corrigi-la, pode abrir um PR que lerei com muito prazer! 😁
Nesse caso eu acredito que se você conseguir pegar essa lista e passar por algum conversor de uppercase para lowercase reduz o trabalho braçal que você teria.
