### ISSUE TITLE
Customers tem campos obrigatórios diferentes de acordo com o tipo de pagamento 

### ISSUE THREAD

**Issue by murilomaiaa** [jonyw4/pagarme-js-types#43]
De acordo com a [documentação](https://docs.pagar.me/docs/realizando-uma-transacao-de-boleto-bancario) o objeto customer para pagamento com boleto segue o seguinte modelo
`customer: {
  type: 'individual',
  country: 'br',
  name: 'Aardvark Silva',
  documents: [
    {
      type: 'cpf',
      number: '00000000000',
    },
  ],
},`

Já para [transações com cartão de crédito](https://docs.pagar.me/docs/realizando-uma-transacao-de-cartao-de-credito) os seguintes campos são obrigatórios
`
      "external_id": "#3311",
     "email": "mopheus@nabucodonozor.com",
      "documents": [
        {
          "type": "cpf",
          "number": "00000000000"
        }
      ],
      "phone_numbers": ["+5511999998888", "+5511888889999"],
      "birthday": "1965-01-01"`

**Comment by jonyw4** [comment]
Para esclarecer melhor o seu problema, acho que seria interessante se você apontasse os campos que estão faltando ou errados e se possível criar um PR.

Hoje[ o código para criação de uma transação está nesse trecho](https://github.com/jonyw4/pagarme-js-types/blob/master/index.d.ts#L570-L655). Perceba que o ele está dividido em partes (boleto, cartão de crédito) e outros que são comum em ambos.

Obs.: No caso quando for referencias alguma documentação, manda [desse link](https://docs.pagar.me/reference#criar-transacao). Esse que você mandou é uma espécie de _tutorial_, quando tem atualização na documentação eles fazem pelo site da referência da API que é esse que mandei. **Confere para ver se o seu problema está nos conformes da referência da API V4.**

**Comment by mrlmaia** [comment]
Esse link que você me mandou é um pouco mais "geral". Ou seja, ele mostra todos os campos possíveis. Já os que eu citei mostram um exemplo mais específico, como você disse, um tutorial, mas, não deixa de ser documentação oficial. Abri os dois links que eu citei e, eles estão na v4. E também testei as mudanças que comentei no projeto que estou implementando. Vou abrir uma PR com as mudanças que eu fiz

**Comment by jonyw4** [comment]
Sim, ele é oficial, mas o link que mandei é o link da referência da documentação, se algo precisar ser alterado provavelmente é lá que eles vão modificar primeiro para depois ir nos tutoriais. Além de que a referência é bem mais completa, com observações sobre quando o campo aparece ou não e outras informações. Então acredito que a longo prazo seria melhor usarmos como parâmetro a referência.

Sobre o PR fique a vontade para criar, apontando a documentação e explicando o que foi modificado eu irei ler e aprovar com muito prazer! =D
