### ISSUE TITLE
mudar o pacote para @types/pagarme

### ISSUE THREAD

**Issue by mrlmaia** [jonyw4/pagarme-js-types#45]
Não conheço muito bem como funciona, mas não tem nenhum jeito de fazer com que se eu desse um `yarn add -D @types/pagarme` esse pacote fosse importado? Ficaria mais fácil para utilizá-lo

**Comment by jonyw4** [comment]
Eu também acho que seria melhor, porém o repositório seria mantido no [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). [Tivemos uma discussão sobre isso lá no repositório do pagarme.](https://github.com/pagarme/pagarme-js/issues/212), se quiser conferir melhor.

Para usar, teríamos que enviar as atualizações para lá. Eu também acho que seria o melhor, mas acredito que para que possamos enviar lá ele tenha que estar completo, e hoje ele está bem longe disso.

**Comment by mpsmarcelo** [comment]
Alguem fez implementação typescript ? Estou com algumas dificuldades para implementar, passando pelos mesmos problemas aqui citados.
