### ISSUE TITLE
Problema ao utilizar a lib 

### ISSUE THREAD

**Issue by emanuelmassafera** [jonyw4/pagarme-js-types#82]
Olá, senhores! Estou tentando utilizar a lib pagarme-js-types, mas estou encontrando problemas. Eu segui todas as orientações presentes no README, instalação da biblioteca e indicação do arquivo de tipagens no tsconfig, no entanto não funcionou para mim. Ao olhar na pasta da biblioteca presente no node_modules, notei que o arquivo que deve ser indicado no tsconfig não se encontra presente. 

![pagarme-js-types](https://user-images.githubusercontent.com/65625500/115558995-ab1dac80-a289-11eb-81dd-e43dd67e21dc.PNG)

Alguém também passou por isso ou sabe como posso proceder? Qualquer orientação será bem-vinda!

**Comment by abrantesarthur** [comment]
Olá @emanuelmassafera . Acredito que eu tenha passado pelo mesmo problema que você. Note que, em `package.json`, o campo `types` tem valor `src/index.d.ts`.  Portanto, o primeiro passo é renomear `index.ts` para `index.d.ts`. Feito isso, em vez de modificar `tsconfig.json` como sugerido nas instruções, modifique da seguinte maneira: no campo `compilerOptions`, adicione um campo `typeRoots` com o seguinte valor: `["node_modules/@types", "node_modules/pagarme-js-types"]`. Isso faz com que o compilador do TypeScript procure por informações de tipo nas pastas especificadas. Você pode encontrar mais informações sobre o que tudo que fiz representa [aqui](https://medium.com/jspoint/typescript-compilation-the-typescript-compiler-4cb15f7244bc)

**Comment by jonyw4** [comment]
Legal @abrantesarthur ! Se puder criar um PR pra corrigir isso eu agradeço 🙏

**Comment by abrantesarthur** [comment]
Sim, claro! Estou implementando e concertando algumas interfaces. Assim que terminar subo um PR relacionado a isso :)

**Comment by emanuelmassafera** [comment]
Excelente! Muito obrigado, @abrantesarthur 👊
